"""create statuses table

Revision ID: 957d3cd81797
Revises: 
Create Date: 2026-07-09 21:55:38.158474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d3cd81797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False))

    with op.batch_alter_table('subprojects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False))

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_status_per_user_per_object',
            ['project_id', 'subproject_id', 'task_id', 'user_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_status_per_user_per_object', type_='unique')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    with op.batch_alter_table('subprojects', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
